# Generated by Django 4.2 on 2024-09-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qianwenpro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Torders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderno", models.CharField(max_length=50)),
                ("descip", models.CharField(max_length=200)),
            ],
        ),
    ]
