# Generated by Django 4.2 on 2024-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qianwenpro", "0002_alter_questions_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("sales", models.IntegerField()),
                ("tags", models.CharField(max_length=200)),
            ],
        ),
    ]
