# Generated by Django 4.2 on 2024-09-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qianwenpro", "0003_cates_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cates",
            name="id",
        ),
        migrations.AddField(
            model_name="cates",
            name="code",
            field=models.CharField(
                default=1, max_length=10, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
