# Generated by Django 4.2 on 2024-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qianwenpro", "0007_remove_resource_customer_roles_customer_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.CharField(default="", max_length=200),
        ),
    ]
