# Generated by Django 5.0.6 on 2024-08-06 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tusers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("money", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.IntegerField(verbose_name="收费")),
                (
                    "docker_types",
                    models.IntegerField(
                        choices=[(1, "3甲"), (2, "普通")], verbose_name="医生类型"
                    ),
                ),
                (
                    "types",
                    models.IntegerField(
                        choices=[(1, "普通"), (2, "极速")], verbose_name="问诊类型"
                    ),
                ),
            ],
            options={
                "verbose_name": "收费",
                "verbose_name_plural": "收费",
            },
        ),
        migrations.CreateModel(
            name="Tusers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("passwd", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=11, unique=True)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("pic_url", models.CharField(max_length=100)),
                ("tscore", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("l_type", models.IntegerField(default=1, verbose_name="积分类型 1加  2减")),
                ("score", models.IntegerField(default=0)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tusers.tusers"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="姓名")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="身份证号"),
                ),
                ("sex", models.IntegerField(verbose_name="性别")),
                ("is_default", models.BooleanField(default=False, verbose_name="是否默认")),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tusers.tusers"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息列表",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "orderno",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("descrip", models.CharField(max_length=255, verbose_name="病情描述")),
                ("times", models.CharField(max_length=30, verbose_name="持续时间")),
                ("pic_url", models.CharField(max_length=200, verbose_name="文件")),
                ("is_into", models.BooleanField(default=False, verbose_name="是否就诊过")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "生成"), (2, "已支付"), (3, "支付失败")],
                        verbose_name="订单状态",
                    ),
                ),
                ("transaction", models.CharField(max_length=50, verbose_name="流水号")),
                (
                    "pay_type",
                    models.IntegerField(
                        choices=[(1, "支付宝"), (2, "微信"), (3, "网银")], verbose_name="支付类型"
                    ),
                ),
                (
                    "docker_types",
                    models.IntegerField(
                        choices=[(1, "3甲"), (2, "普通")], verbose_name="医生类型"
                    ),
                ),
                (
                    "types",
                    models.IntegerField(
                        choices=[(1, "普通"), (2, "极速")], verbose_name="问诊类型"
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("couponid", models.IntegerField(default=0)),
                ("couponmoney", models.IntegerField(default=0)),
                ("tmoney", models.IntegerField(default=0)),
                ("pay_money", models.IntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tusers.department",
                        verbose_name="科室id",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tusers.patient",
                        verbose_name="患者id",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tusers.tusers",
                        verbose_name="用户id",
                    ),
                ),
            ],
            options={
                "verbose_name": "咨询订单",
                "verbose_name_plural": "咨询订单",
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("money", models.IntegerField(default=0)),
                ("status", models.IntegerField(default=1)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tusers.coupon"
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tusers.tusers"
                    ),
                ),
            ],
        ),
    ]
