# Generated by Django 5.0.6 on 2024-08-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tusers", "0002_coupon_fee_tusers_score_patient_orders_usercoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="tusers",
            name="lock_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
