# Generated by Django 5.0.6 on 2024-07-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name": "测试角色表",
                "verbose_name_plural": "测试角色表",
                "db_table": "testrole",
            },
        ),
    ]
